#!/usr/bin/env bash
set -euo pipefail

export PYTHONUNBUFFERED=1
export PYTORCH_ALLOC_CONF=${PYTORCH_ALLOC_CONF:-expandable_segments:True}

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
SANDBOX_ENV_DIR="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
SLIME_EXAMPLES_DIR="$(cd -- "${SANDBOX_ENV_DIR}/.." && pwd)"
SLIME_DIR_DEFAULT="$(cd -- "${SLIME_EXAMPLES_DIR}/.." && pwd)"
WORKSPACE_ROOT="$(cd -- "${SLIME_DIR_DEFAULT}/.." && pwd)"
AVALANCHE_ROOT="$(cd -- "${WORKSPACE_ROOT}/.." && pwd)"

# shellcheck disable=SC1091
source "${WORKSPACE_ROOT}/login.sh"

NUM_NODES=1
NUM_GPUS_PER_NODE=8
ACTOR_NUM_NODES=1
ACTOR_GPUS_PER_NODE=4
ROLLOUT_GPUS_TOTAL=4
MASTER_ADDR=127.0.0.1

MODEL_NAME=Qwen3.5-35B-A3B
MODEL_DIR="${AVALANCHE_ROOT}/models/${MODEL_NAME}"
TORCH_DIST_DIR="${AVALANCHE_ROOT}/models/${MODEL_NAME}_torch_dist"

SLIME_DIR="${SLIME_DIR_DEFAULT}"
MEGATRON_PATH=/root/Megatron-LM
INSPIRE_SANDBOX_SITE_PACKAGES="${AVALANCHE_ROOT}/.local/share/inspire_sandbox_site_packages"
SHARE_WORKSPACE="${AVALANCHE_ROOT}/share_workspace"
REBENCH_TASKS_JSON="${REBENCH_TASKS_JSON:-${AVALANCHE_ROOT}/data/raw_data/single/swe_rebench_v2/data/train-00000-of-00001.json}"
SWE_CONSUMABLE_TEMPLATE_MANIFEST="${SWE_CONSUMABLE_TEMPLATE_MANIFEST:-${SANDBOX_ENV_DIR}/data_output/swe_rebench_scaffold_template_smoke_gc2.jsonl}"

SWE_AGENT_HARNESS="${SWE_AGENT_HARNESS:-codex}"
SWE_USE_WANDB=0
SWE_WANDB_PROJECT=slime-swe
SWE_WANDB_GROUP="${SWE_WANDB_GROUP:-qwen3.5-35b-a3b-1node-smoke-${SWE_AGENT_HARNESS}}"
SWE_WANDB_RUN_ID="${SWE_WANDB_RUN_ID:-${SWE_WANDB_GROUP}}"

WORK_ROOT_BASE="${WORK_ROOT_BASE:-${SANDBOX_ENV_DIR}/output/qwen3_5_35b_1node}"
RUN_DIR_NAME="${SWE_WANDB_GROUP//\//_}"
RUN_DIR_NAME="${RUN_DIR_NAME// /_}-${SWE_AGENT_HARNESS}"
WORK_ROOT="${WORK_ROOT_BASE}/${RUN_DIR_NAME}"
DATA_CACHE_DIR="${WORK_ROOT}/data_cache"
LOG_DIR="${WORK_ROOT}/logs"
SAVE_DIR="${WORK_ROOT}/checkpoints"
NORMALIZED_TRAIN="${DATA_CACHE_DIR}/swe_train.normalized.jsonl"
NORMALIZED_VAL="${DATA_CACHE_DIR}/swe_val.normalized.jsonl"
JOB_ENTRYPOINT_SCRIPT="${WORK_ROOT}/run_train_async_job.sh"
SWE_LOG_ROOT="${LOG_DIR}"

SWE_TRAIN_MAX_PER_SOURCE="${SWE_TRAIN_MAX_PER_SOURCE:-8}"
SWE_VAL_MAX_PER_SOURCE="${SWE_VAL_MAX_PER_SOURCE:-0}"
SWE_SHUFFLE_DATA="${SWE_SHUFFLE_DATA:-0}"
SWE_DATA_SEED="${SWE_DATA_SEED:-42}"
SWE_REQUIRE_CONSUMABLE_TEMPLATES="${SWE_REQUIRE_CONSUMABLE_TEMPLATES:-1}"

SWE_MODEL_PROXY_PORT=30001
SWE_WSTUNNEL_SERVER_PORT=19090

SWE_NUM_ROLLOUT="${SWE_NUM_ROLLOUT:-1}"
SWE_ROLLOUT_BATCH_SIZE="${SWE_ROLLOUT_BATCH_SIZE:-1}"
SWE_SAMPLES_PER_PROMPT="${SWE_SAMPLES_PER_PROMPT:-1}"
SWE_MICRO_BATCH_SIZE="${SWE_MICRO_BATCH_SIZE:-1}"
SWE_STEPS_PER_ROLLOUT="${SWE_STEPS_PER_ROLLOUT:-1}"
SWE_GLOBAL_BATCH_SIZE="${SWE_GLOBAL_BATCH_SIZE:-1}"
SWE_MAX_CONTEXT_LEN="${SWE_MAX_CONTEXT_LEN:-32768}"
SWE_MAX_RESPONSE_LEN="${SWE_MAX_RESPONSE_LEN:-4096}"
SWE_OVER_SAMPLING_BATCH_SIZE="${SWE_OVER_SAMPLING_BATCH_SIZE:-1}"
SWE_GROUP_CONCURRENCY="${SWE_GROUP_CONCURRENCY:-1}"
SWE_SAMPLE_CONCURRENCY="${SWE_SAMPLE_CONCURRENCY:-1}"

SWE_LR=1e-6
SWE_ADAM_BETA2=0.98
SWE_KL_LOSS_COEF=0.0

SWE_TENSOR_MODEL_PARALLEL_SIZE=2
SWE_CONTEXT_PARALLEL_SIZE=2
SWE_EXPERT_MODEL_PARALLEL_SIZE=4
SWE_ROLLOUT_NUM_GPUS_PER_ENGINE=4
SWE_SGLANG_EP_SIZE=4
SWE_SGLANG_MEM_FRACTION_STATIC=0.55
SWE_MAX_TOKENS_PER_GPU=1024
SWE_USE_DYNAMIC_BATCH_SIZE=1

SWE_OPTIMIZER_CPU_OFFLOAD=1
SWE_OVERLAP_CPU_OPTIMIZER_D2H_H2D=1
SWE_USE_PRECISION_AWARE_OPTIMIZER=1

SWE_MAX_TURNS="${SWE_MAX_TURNS:-100}"
SWE_AGENT_FINISH_TIMEOUT="${SWE_AGENT_FINISH_TIMEOUT:-3600}"
SWE_WAIT_TIMEOUT=3600
SWE_KEEP_CONTAINERS=0
SWE_SANDBOX_START_RETRY_TIMES=3
SWE_SANDBOX_START_RETRY_INTERVAL=5

SWE_RESUME_TRAINING=0
SWE_LOAD_DIR=""
SWE_DEBUG_ROLLOUT_ONLY="${SWE_DEBUG_ROLLOUT_ONLY:-1}"
FORCE_REBUILD_TORCH_DIST=0

# shellcheck disable=SC1091
source "${SCRIPT_DIR}/swe_train_lib.sh"
