#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd -- "${SCRIPT_DIR}/../../.." && pwd)"
AVALANCHE_ROOT="$(cd -- "${PROJECT_ROOT}/.." && pwd)"

source "${PROJECT_ROOT}/login.sh"

RESOURCE="${RESOURCE:-8xH100}"
PRIORITY="${PRIORITY:-10}"
MAX_TIME="${MAX_TIME:-168}"
FAULT_TOLERANT="${FAULT_TOLERANT:-1}"
JOB_NAME="${JOB_NAME:-multidomain-v2-3node-$(date '+%m%d-%H%M')}"
SUBMIT_NODES="${SUBMIT_NODES:-3}"
IMAGE="${IMAGE:-${INSP_IMAGE:-}}"
WORKSPACE_ID="${WORKSPACE_ID:-ws-9dcc0e1f-80a4-4af2-bc2f-0e352e7b17e6}"
WORK_ROOT_VALUE="${WORK_ROOT:-${AVALANCHE_ROOT}/experiments/multidomain_v2_3node}"
REMOTE_ROOT_DEFAULT="${INSPIRE_TARGET_DIR:-${PROJECT_ROOT}}"
REMOTE_ROOT="${REMOTE_ROOT:-${REMOTE_ROOT_DEFAULT}}"
JOB_LOG_ROOT="${JOB_LOG_ROOT:-${WORK_ROOT_VALUE}/logs}"
UV_VENV_DIR="${UV_VENV_DIR:-${REMOTE_ROOT}/.nemo_gym_venvs}"
RUN_SCRIPT="examples/multidomain_v2/run_qwen3_30b_a3b_multidomain_v2_3node.sh"
RUN_SCRIPT_FALLBACK="slime/${RUN_SCRIPT}"

FORWARDED_ENV_VARS=(
  JOB_NAME
  WORK_ROOT
  MODEL_DIR
  TORCH_DIST_DIR
  TRAIN_POOL_ROOT
  TRAIN_POOL_DATASETS
  NUM_NODES
  ACTOR_NUM_NODES
  ACTOR_GPUS_PER_NODE
  ROLLOUT_GPUS_TOTAL
  TOOLCALL_ROLLOUT_BATCH_SIZE
  TOOLCALL_SAMPLES_PER_PROMPT
  TOOLCALL_GLOBAL_BATCH_SIZE
  TOOLCALL_STEPS_PER_ROLLOUT
  TOOLCALL_MAX_CONTEXT_LEN
  TOOLCALL_MAX_RESPONSE_LEN
  TOOLCALL_MAX_PROMPT_TOKENS
  TOOLCALL_PARSER_TYPE
  TOOLCALL_LR
  TOOLCALL_ADAM_BETA2
  TOOLCALL_COLOCATE
  TOOLCALL_DYNAMIC_FILTER
  TOOLCALL_USE_ROUTING_REPLAY
  TOOLCALL_USE_ROLLOUT_ROUTING_REPLAY
  TOOLCALL_RESUME_TRAINING
  TOOLCALL_RESUME_NO_OPTIM
  TOOLCALL_RESUME_NO_RNG
  TOOLCALL_RESUME_FINETUNE
  TOOL_CALL_LOAD_DIR
  TOOL_CALL_WANDB_PROJECT
  TOOL_CALL_WANDB_GROUP
  EVAL_BFCL_V3_SAMPLES
  EVAL_BFCL_MULTI_TURN_SAMPLES
  EVAL_IFEVAL_SAMPLES
  EVAL_JSONSCHEMABENCH_SAMPLES
  EVAL_IFBENCH_TEST_SAMPLES
  EVAL_MMLU_PRO_SAMPLES
  EVAL_GPQA_MAIN_SAMPLES
  RAY_CLUSTER_WAIT_MAX_ATTEMPTS
  RAY_CLUSTER_WAIT_SLEEP_SECONDS
  RAY_CLUSTER_STATUS_TIMEOUT_SECONDS
  RAY_WORKER_JOIN_MAX_ATTEMPTS
  RAY_WORKER_JOIN_RETRY_SLEEP_SECONDS
  RAY_HEAD_ADDR_WAIT_ATTEMPTS
  RAY_HEAD_ADDR_WAIT_SLEEP
  RAY_HEAD_START_STATUS_MAX_ATTEMPTS
  RAY_HEAD_START_STATUS_SLEEP_SECONDS
  RAY_GCS_RPC_SERVER_RECONNECT_TIMEOUT_SECONDS
  RAY_gcs_rpc_server_reconnect_timeout_s
  WANDB_API_KEY
  WANDB_BASE_URL
  UV_VENV_DIR
)

# shellcheck source=/dev/null
source "${SCRIPT_DIR}/../_shared/submit_inspire_utils.sh"

submit_inspire_job
