#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd -- "${SCRIPT_DIR}/../../.." && pwd)"

source "${PROJECT_ROOT}/login.sh"

RESOURCE="${RESOURCE:-8xH100}"
PRIORITY="${PRIORITY:-10}"
MAX_TIME="${MAX_TIME:-24}"
JOB_NAME="${JOB_NAME:-multidomain-v2-3node-$(date '+%m%d-%H%M')}"
SUBMIT_NODES="${SUBMIT_NODES:-3}"
IMAGE="${IMAGE:-${INSP_IMAGE:-}}"
WORKSPACE_ID="${WORKSPACE_ID:-ws-9dcc0e1f-80a4-4af2-bc2f-0e352e7b17e6}"
REMOTE_ROOT="${INSPIRE_TARGET_DIR:-${PROJECT_ROOT}}"
UV_VENV_DIR="${UV_VENV_DIR:-${REMOTE_ROOT}/.nemo_gym_venvs}"
RUN_SCRIPT="slime/examples/multidomain_v2/run_qwen3_30b_a3b_multidomain_v2_3node.sh"

FORWARDED_ENV_VARS=(
  JOB_NAME
  WORK_ROOT
  MODEL_DIR
  TORCH_DIST_DIR
  TRAIN_POOL_ROOT
  TRAIN_DATA_BASENAME
  NUM_NODES
  ACTOR_NUM_NODES
  ACTOR_GPUS_PER_NODE
  ROLLOUT_GPUS_TOTAL
  TOOLCALL_ROLLOUT_BATCH_SIZE
  TOOLCALL_SAMPLES_PER_PROMPT
  TOOLCALL_GLOBAL_BATCH_SIZE
  TOOLCALL_STEPS_PER_ROLLOUT
  TOOLCALL_MAX_CONTEXT_LEN
  TOOLCALL_MAX_RESPONSE_LEN
  TOOLCALL_MAX_PROMPT_TOKENS
  TOOLCALL_PARSER_TYPE
  TOOLCALL_LR
  TOOLCALL_ADAM_BETA2
  TOOLCALL_COLOCATE
  TOOLCALL_RESUME_TRAINING
  TOOLCALL_RESUME_NO_OPTIM
  TOOLCALL_RESUME_NO_RNG
  TOOLCALL_RESUME_FINETUNE
  TOOL_CALL_LOAD_DIR
  TOOL_CALL_WANDB_PROJECT
  TOOL_CALL_WANDB_GROUP
  EVAL_BFCL_V3_SAMPLES
  EVAL_BFCL_MULTI_TURN_SAMPLES
  EVAL_TOOLBENCH_BENCHMARK_SAMPLES
  EVAL_IFEVAL_SAMPLES
  EVAL_JSONSCHEMABENCH_SAMPLES
  EVAL_IFBENCH_TEST_SAMPLES
  EVAL_MMLU_PRO_SAMPLES
  EVAL_GPQA_MAIN_SAMPLES
  WANDB_API_KEY
  WANDB_BASE_URL
  UV_VENV_DIR
)

RUN_ENV_EXPORTS=""
for var_name in "${FORWARDED_ENV_VARS[@]}"; do
  if [[ -n "${!var_name+x}" ]]; then
    RUN_ENV_EXPORTS+=" export ${var_name}=$(printf '%q' "${!var_name}");"
  fi
done
RUN_CMD="cd ${REMOTE_ROOT} &&${RUN_ENV_EXPORTS} bash ${RUN_SCRIPT}"

CMD=(
  "$INSPIRE_CLI" job create
  --name "${JOB_NAME}"
  --resource "${RESOURCE}"
  --nodes "${SUBMIT_NODES}"
  --priority "${PRIORITY}"
  --max-time "${MAX_TIME}"
  --no-auto
  --command "${RUN_CMD}"
)

if [[ -n "${IMAGE}" ]]; then
  CMD+=(--image "${IMAGE}")
fi

if [[ -n "${WORKSPACE_ID}" ]]; then
  CMD+=(--workspace-id "${WORKSPACE_ID}")
fi

"${CMD[@]}"
