import logging

from slime.utils.mask_utils import MultiTurnLossMaskGenerator
from slime.utils.processing_utils import load_processor, load_tokenizer

__all__ = ["generate_rollout"]

logger = logging.getLogger(__name__)


TOKENIZER = None
PROCESSOR = None
MASK_GENERATOR = None
SAMPLE_PRINTED = False


def generate_rollout(args, rollout_id, data_buffer, evaluation=False):
    """An example to implement the generate_rollout function for an rule based rm rollout generation.

    Args:
        args: the whole args
        rollout_id: int, the id of the rollout, used for deterministic data generation
        data_buffer: the data buffer to store the generated samples
        evaluation: bool, whether the rollout is for evaluation or not

    Returns:
        list[Sample]: a list of samples generated by the rollout
    """
    assert not evaluation
    assert args.rollout_global_dataset

    global TOKENIZER, PROCESSOR, MASK_GENERATOR, SAMPLE_PRINTED
    if TOKENIZER is None:
        TOKENIZER = load_tokenizer(args.hf_checkpoint, trust_remote_code=True)

    if PROCESSOR is None:
        PROCESSOR = load_processor(args.hf_checkpoint, trust_remote_code=True)

    if MASK_GENERATOR is None:
        MASK_GENERATOR = MultiTurnLossMaskGenerator(
            TOKENIZER,
            chat_template_kwargs=args.apply_chat_template_kwargs,
            chat_template_processor=PROCESSOR,
        )

    samples = data_buffer.get_samples(args.rollout_batch_size)

    for i, sample in enumerate(samples):
        (sample,) = sample
        messages = sample.prompt
        tools = sample.metadata.get("tools", None)

        mask_result = MASK_GENERATOR.get_loss_mask_result(messages, tools=tools)
        if len(mask_result.token_ids) != len(mask_result.loss_mask):
            raise ValueError(
                "SFT rollout produced mismatched token_ids/loss_mask lengths: "
                f"len(token_ids)={len(mask_result.token_ids)}, len(loss_mask)={len(mask_result.loss_mask)}"
            )

        response_length = mask_result.response_length

        sample.tokens = mask_result.token_ids
        sample.response_length = response_length
        sample.reward = 0
        sample.loss_mask = mask_result.response_loss_mask

        if i == 0 and not SAMPLE_PRINTED:
            logger.info(
                "sft_rollout::generate_rollout example data: "
                f"{sample=} (raw){messages=} (raw){mask_result.token_ids=} "
                f"(raw){mask_result.loss_mask=} {response_length=}"
            )
            SAMPLE_PRINTED = True

    return samples
