#!/usr/bin/env bash
# Submit MOPD 4-node job to Inspire.
#
# Usage:
#   bash slime/examples/MOPD/submit_mopd_qwen3_30b_4node.sh
#
# Override env vars as needed:
#   JOB_NAME=mopd-test RESOURCE=8xH100 bash slime/examples/MOPD/submit_mopd_qwen3_30b_4node.sh

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd -- "${SCRIPT_DIR}/../../.." && pwd)"
AVALANCHE_ROOT="$(cd -- "${PROJECT_ROOT}/.." && pwd)"

if [[ -f "${PROJECT_ROOT}/login.sh" ]]; then
  # shellcheck source=/dev/null
  source "${PROJECT_ROOT}/login.sh"
fi

RESOURCE="${RESOURCE:-8xH100}"
PRIORITY="${PRIORITY:-10}"
MAX_TIME="${MAX_TIME:-168}"
JOB_NAME="${JOB_NAME:-mopd-4node-$(date '+%m%d-%H%M')}"
SUBMIT_NODES="${SUBMIT_NODES:-4}"
IMAGE="${IMAGE:-${INSP_IMAGE:-docker.sii.shaipower.online/inspire-studio/slime-avalanche:0.0.2}}"
WORKSPACE_ID="${WORKSPACE_ID:-ws-9dcc0e1f-80a4-4af2-bc2f-0e352e7b17e6}"
WORK_ROOT_VALUE="${WORK_ROOT:-${AVALANCHE_ROOT}/experiments/mopd_qwen3_30b_a3b_4node_pool_direct}"
REMOTE_ROOT_DEFAULT="${INSPIRE_TARGET_DIR:-${PROJECT_ROOT}}"
REMOTE_ROOT="${REMOTE_ROOT:-${REMOTE_ROOT_DEFAULT}}"
JOB_LOG_ROOT="${JOB_LOG_ROOT:-${WORK_ROOT_VALUE}/logs}"
RUN_SCRIPT="examples/MOPD/run_mopd_qwen3_30b_4node.sh"
RUN_SCRIPT_FALLBACK="slime/${RUN_SCRIPT}"

FORWARDED_ENV_VARS=(
  JOB_NAME
  WORK_ROOT
  MODEL_DIR
  TORCH_DIST_DIR
  STUDENT_CKPT_STEP
  NUM_NODES
  ACTOR_NUM_NODES
  ACTOR_GPUS_PER_NODE
  ROLLOUT_GPUS_TOTAL
  TRAIN_POOL_ROOT
  TRAIN_POOL_INCLUDE_DOMAINS
  TRAIN_POOL_EXCLUDE_PATTERNS
  TRAIN_SOURCE_LIST_BASENAME
  SGLANG_MULTIMODEL_CONFIG
  OPD_DOMAIN_MODEL_MAP
  TOOLCALL_ROLLOUT_BATCH_SIZE
  TOOLCALL_SAMPLES_PER_PROMPT
  TOOLCALL_GLOBAL_BATCH_SIZE
  TOOLCALL_STEPS_PER_ROLLOUT
  TOOLCALL_MAX_CONTEXT_LEN
  TOOLCALL_MAX_RESPONSE_LEN
  TOOLCALL_PARSER_TYPE
  TOOLCALL_LR
  TOOLCALL_ADAM_BETA2
  TOOLCALL_USE_ROLLOUT_ROUTING_REPLAY
  OPD_KL_COEF
  KL_LOSS_COEF
  TOOLCALL_RESUME_TRAINING
  TOOLCALL_RESUME_NO_OPTIM
  TOOLCALL_RESUME_NO_RNG
  TOOLCALL_RESUME_FINETUNE
  TOOL_CALL_WANDB_PROJECT
  TOOL_CALL_WANDB_GROUP
  RAY_CLUSTER_WAIT_MAX_ATTEMPTS
  RAY_CLUSTER_WAIT_SLEEP_SECONDS
  RAY_CLUSTER_STATUS_TIMEOUT_SECONDS
  RAY_WORKER_JOIN_MAX_ATTEMPTS
  RAY_WORKER_JOIN_RETRY_SLEEP_SECONDS
  RAY_HEAD_ADDR_WAIT_ATTEMPTS
  RAY_HEAD_ADDR_WAIT_SLEEP
  RAY_HEAD_START_STATUS_MAX_ATTEMPTS
  RAY_HEAD_START_STATUS_SLEEP_SECONDS
  RAY_GCS_RPC_SERVER_RECONNECT_TIMEOUT_SECONDS
  RAY_gcs_rpc_server_reconnect_timeout_s
  WANDB_API_KEY
  WANDB_BASE_URL
)

customize_run_env_exports() {
  local run_env_exports="$1"
  if [[ -z "${TOOLCALL_USE_ROLLOUT_ROUTING_REPLAY+x}" ]]; then
    run_env_exports+=" export TOOLCALL_USE_ROLLOUT_ROUTING_REPLAY=0;"
  fi
  printf '%s' "${run_env_exports}"
}

# shellcheck source=/dev/null
source "${SCRIPT_DIR}/../_shared/submit_inspire_utils.sh"

submit_inspire_job
