#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd -- "${SCRIPT_DIR}/../../.." && pwd)"
AVALANCHE_ROOT="$(cd -- "${PROJECT_ROOT}/.." && pwd)"

if [[ -f "${PROJECT_ROOT}/login.sh" ]]; then
  # shellcheck source=/dev/null
  source "${PROJECT_ROOT}/login.sh"
fi

INSPIRE_BIN="${INSPIRE_CLI:-inspire}"
RUN_TAG="${RUN_TAG:-$(date '+%m%d-%H%M')}"
JOB_NAME="${JOB_NAME:-mopd-3node-h200-${RUN_TAG}}"
WORK_ROOT="${WORK_ROOT:-${AVALANCHE_ROOT}/experiments/${JOB_NAME}}"
RESOURCE="${RESOURCE:-8xH200}"
PRIORITY="${PRIORITY:-10}"
MAX_TIME="${MAX_TIME:-168}"
SUBMIT_NODES="${SUBMIT_NODES:-3}"
IMAGE="${IMAGE:-${INSP_IMAGE:-docker.sii.shaipower.online/inspire-studio/slime-avalanche:0.0.2}}"
WORKSPACE_ID="${WORKSPACE_ID:-ws-9dcc0e1f-80a4-4af2-bc2f-0e352e7b17e6}"
REMOTE_ROOT_DEFAULT="${INSPIRE_TARGET_DIR:-${PROJECT_ROOT}}"
REMOTE_ROOT="${REMOTE_ROOT:-${REMOTE_ROOT_DEFAULT}}"
JOB_LOG_ROOT="${JOB_LOG_ROOT:-${WORK_ROOT}/logs}"
RUN_SCRIPT="examples/MOPD/run_mopd_qwen3_30b_3node_h200.sh"
RUN_SCRIPT_FALLBACK="slime/${RUN_SCRIPT}"

export JOB_NAME WORK_ROOT
export NUM_NODES="${NUM_NODES:-3}"
export ACTOR_NUM_NODES="${ACTOR_NUM_NODES:-2}"
export ACTOR_GPUS_PER_NODE="${ACTOR_GPUS_PER_NODE:-8}"
export ROLLOUT_GPUS_TOTAL="${ROLLOUT_GPUS_TOTAL:-7}"
export EVAL_INTERVAL="${EVAL_INTERVAL:-10}"
export TEACHER_STEP0_EVAL="${TEACHER_STEP0_EVAL:-1}"
export TOOLCALL_USE_ROLLOUT_ROUTING_REPLAY="${TOOLCALL_USE_ROLLOUT_ROUTING_REPLAY:-1}"
export SGLANG_MULTIMODEL_CONFIG="${SGLANG_MULTIMODEL_CONFIG:-${SCRIPT_DIR}/sglang_mopd_qwen3_30b_3node_h200.yaml}"
export TOOL_TEACHER_EXP_DIR="${TOOL_TEACHER_EXP_DIR:-${AVALANCHE_ROOT}/experiments/multidomain_v2_main_retry}"
export TOOL_TEACHER_CKPT_STEP="${TOOL_TEACHER_CKPT_STEP:-279}"
export TOOL_TEACHER_TORCH_DIST_DIR="${TOOL_TEACHER_TORCH_DIST_DIR:-${TOOL_TEACHER_EXP_DIR}/checkpoints}"
export TOOL_TEACHER_ORIGIN_HF="${TOOL_TEACHER_ORIGIN_HF:-${TOOL_TEACHER_EXP_DIR}/hf_cache/iter_0000299_hf}"
export TOOL_TEACHER_HF_DIR="${TOOL_TEACHER_HF_DIR:-${TOOL_TEACHER_EXP_DIR}/hf_cache/iter_0000279_hf}"
export CODE_TEACHER_HF_DIR="${CODE_TEACHER_HF_DIR:-/inspire/qb-ilm/project/cq-scientific-cooperation-zone/public/avalanche/jl_workspace/experiment/code/output/qwen3-30b-a3b-code-3node/hf_cache/iter_0000099_hf}"
export MATH_TEACHER_HF_DIR="${MATH_TEACHER_HF_DIR:-/inspire/qb-ilm/project/cq-scientific-cooperation-zone/public/avalanche/jl_workspace/experiment/math/output/qwen3-30b-a3b-deepmath-3node/hf_cache/iter_0000339_hf}"
export TOOL_CALL_WANDB_GROUP="${TOOL_CALL_WANDB_GROUP:-${JOB_NAME}}"

FORWARDED_ENV_VARS=(
  JOB_NAME WORK_ROOT MODEL_DIR TORCH_DIST_DIR STUDENT_CKPT_STEP EVAL_INTERVAL
  NUM_NODES ACTOR_NUM_NODES ACTOR_GPUS_PER_NODE ROLLOUT_GPUS_TOTAL
  TRAIN_POOL_ROOT TRAIN_POOL_INCLUDE_DOMAINS TRAIN_POOL_EXCLUDE_PATTERNS TRAIN_SOURCE_LIST_BASENAME
  SGLANG_MULTIMODEL_CONFIG OPD_DOMAIN_MODEL_MAP TOOLCALL_ROLLOUT_BATCH_SIZE TOOLCALL_SAMPLES_PER_PROMPT
  TOOLCALL_GLOBAL_BATCH_SIZE TOOLCALL_STEPS_PER_ROLLOUT TOOLCALL_MAX_CONTEXT_LEN TOOLCALL_MAX_RESPONSE_LEN
  TOOLCALL_PARSER_TYPE TOOLCALL_LR TOOLCALL_ADAM_BETA2 TOOLCALL_USE_ROLLOUT_ROUTING_REPLAY OPD_KL_COEF
  KL_LOSS_COEF TOOLCALL_RESUME_TRAINING TOOLCALL_RESUME_NO_OPTIM TOOLCALL_RESUME_NO_RNG TOOLCALL_RESUME_FINETUNE
  TOOL_TEACHER_EXP_DIR TOOL_TEACHER_CKPT_STEP TOOL_TEACHER_TORCH_DIST_DIR TOOL_TEACHER_ORIGIN_HF TOOL_TEACHER_HF_DIR
  CODE_TEACHER_HF_DIR MATH_TEACHER_HF_DIR TEACHER_STEP0_EVAL TEACHER_STEP0_EVAL_PORT_BASE TEACHER_STEP0_EVAL_BATCH_SIZE
  TOOL_CALL_WANDB_PROJECT TOOL_CALL_WANDB_GROUP RAY_CLUSTER_WAIT_MAX_ATTEMPTS RAY_CLUSTER_WAIT_SLEEP_SECONDS
  RAY_CLUSTER_STATUS_TIMEOUT_SECONDS RAY_WORKER_JOIN_MAX_ATTEMPTS RAY_WORKER_JOIN_RETRY_SLEEP_SECONDS
  RAY_HEAD_ADDR_WAIT_ATTEMPTS RAY_HEAD_ADDR_WAIT_SLEEP RAY_HEAD_START_STATUS_MAX_ATTEMPTS RAY_HEAD_START_STATUS_SLEEP_SECONDS
  RAY_GCS_RPC_SERVER_RECONNECT_TIMEOUT_SECONDS RAY_gcs_rpc_server_reconnect_timeout_s WANDB_API_KEY WANDB_BASE_URL
)

RUN_ENV_EXPORTS=""
for var_name in "${FORWARDED_ENV_VARS[@]}"; do
  if [[ -n "${!var_name+x}" ]]; then
    RUN_ENV_EXPORTS+=" export ${var_name}=$(printf '%q' "${!var_name}");"
  fi
done
RUN_CMD="cd ${REMOTE_ROOT} &&${RUN_ENV_EXPORTS} if [[ -f \"${RUN_SCRIPT}\" ]]; then bash ${RUN_SCRIPT}; elif [[ -f \"${RUN_SCRIPT_FALLBACK}\" ]]; then bash ${RUN_SCRIPT_FALLBACK}; else echo \"Run script not found: ${RUN_SCRIPT} or ${RUN_SCRIPT_FALLBACK}\" >&2; exit 1; fi"

CMD=(
  "${INSPIRE_BIN}" job create
  --name "${JOB_NAME}"
  --resource "${RESOURCE}"
  --nodes "${SUBMIT_NODES}"
  --priority "${PRIORITY}"
  --max-time "${MAX_TIME}"
  --no-auto
  --command "${RUN_CMD}"
)

if [[ -n "${IMAGE}" ]]; then
  CMD+=(--image "${IMAGE}")
fi
if [[ -n "${WORKSPACE_ID}" ]]; then
  CMD+=(--workspace-id "${WORKSPACE_ID}")
fi

SUBMIT_CWD="${SUBMIT_CWD:-${TMPDIR:-/tmp}}"
(
  cd "${SUBMIT_CWD}"
  export INSPIRE_TARGET_DIR="${JOB_LOG_ROOT}"
  "${CMD[@]}"
)
